### PR TITLE
Data and changes for the 2023 season

### PR DESCRIPTION
**Pull request by srobbin**

### CODE REVIEW

**Comment by agoeckner** [comment]
Awesome, thank you for running this, man. Do you think the website will be ready soon? (appears to be down right now)

**Comment by cubedmeatgoeshere** [comment]
Streets and San really taking their sweet time publishing the 2023 schedule, already 2 weeks behind! How expedient have they been in prior years?

**Comment by cubedmeatgoeshere** [comment]
Thanks for your continued work on this!

In the interim we can always use: https://www.chicago.gov/city/en/depts/streets/provdrs/streets_san/svcs/street_sweeping2023.html

**Comment by srobbin** [comment]
@agoeckner, @cubedmeatgoeshere Thanks for checking in. I've been meaning to post an update, but in a strange sequence of events, it looks like I can no longer send emails from the @sweeparound.us domain. Apparently, some time over the winter, Google banned the domain, and now rejects all emails sent to Gmail. Unfortunately, I think this may be the final nail in the coffin for SweepAround.Us. I'm talking to some folks to see if they're interested in taking the project over, and starting a new service. If anything comes of that, I'll be sure to notify you here.

**Comment by agoeckner** [comment]
Sad news indeed. I wonder if it can be implemented as an RSS feed which does not require email?

**Comment by srobbin** [comment]
Closed in favor of #3. The service is still down right now, but these changes should make it easier for other developers to get up and running.

**Pull request closed without merging**
